class CreateCategories < ActiveRecord::Migration
  def self.up
    create_table :categories do |t|
      t.integer :parent_id
    end
    
    c = Category.new(:parent_id => nil);c.id = 1;c.save
    c = Category.new(:parent_id => 878);c.id = 11;c.save
    c = Category.new(:parent_id => 1);c.id = 12;c.save
    c = Category.new(:parent_id => 14);c.id = 13;c.save
    c = Category.new(:parent_id => 1);c.id = 14;c.save
    c = Category.new(:parent_id => 16);c.id = 15;c.save
    c = Category.new(:parent_id => 1);c.id = 16;c.save
    c = Category.new(:parent_id => 1);c.id = 18;c.save
    c = Category.new(:parent_id => 18);c.id = 19;c.save
    c = Category.new(:parent_id => 1);c.id = 22;c.save
    c = Category.new(:parent_id => 1);c.id = 27;c.save
    c = Category.new(:parent_id => 1);c.id = 28;c.save
    c = Category.new(:parent_id => 36);c.id = 31;c.save
    c = Category.new(:parent_id => 36);c.id = 32;c.save
    c = Category.new(:parent_id => 19);c.id = 33;c.save
    c = Category.new(:parent_id => 16);c.id = 34;c.save
    c = Category.new(:parent_id => 1);c.id = 35;c.save
    c = Category.new(:parent_id => 1);c.id = 36;c.save
    c = Category.new(:parent_id => 1);c.id = 37;c.save
    c = Category.new(:parent_id => 35);c.id = 38;c.save
    c = Category.new(:parent_id => 27);c.id = 39;c.save
    c = Category.new(:parent_id => 37);c.id = 40;c.save
    c = Category.new(:parent_id => 878);c.id = 43;c.save
    c = Category.new(:parent_id => 18);c.id = 44;c.save
    c = Category.new(:parent_id => 878);c.id = 51;c.save
    c = Category.new(:parent_id => 878);c.id = 52;c.save
    c = Category.new(:parent_id => 1);c.id = 53;c.save
    c = Category.new(:parent_id => 18);c.id = 54;c.save
    c = Category.new(:parent_id => 35);c.id = 56;c.save
    c = Category.new(:parent_id => 878);c.id = 57;c.save
    c = Category.new(:parent_id => 18);c.id = 69;c.save
    c = Category.new(:parent_id => 18);c.id = 71;c.save
    c = Category.new(:parent_id => 22);c.id = 72;c.save
    c = Category.new(:parent_id => 53);c.id = 76;c.save
    c = Category.new(:parent_id => 53);c.id = 79;c.save
    c = Category.new(:parent_id => 1);c.id = 80;c.save
    c = Category.new(:parent_id => 82);c.id = 81;c.save
    c = Category.new(:parent_id => 1);c.id = 82;c.save
    c = Category.new(:parent_id => 158);c.id = 86;c.save
    c = Category.new(:parent_id => 12);c.id = 89;c.save
    c = Category.new(:parent_id => 18);c.id = 92;c.save
    c = Category.new(:parent_id => 1);c.id = 99;c.save
    c = Category.new(:parent_id => 99);c.id = 101;c.save
    c = Category.new(:parent_id => 105);c.id = 103;c.save
    c = Category.new(:parent_id => 1);c.id = 105;c.save
    c = Category.new(:parent_id => 53);c.id = 106;c.save
    c = Category.new(:parent_id => 35);c.id = 114;c.save
    c = Category.new(:parent_id => 114);c.id = 115;c.save
    c = Category.new(:parent_id => 114);c.id = 116;c.save
    c = Category.new(:parent_id => 114);c.id = 117;c.save
    c = Category.new(:parent_id => 35);c.id = 119;c.save
    c = Category.new(:parent_id => 35);c.id = 121;c.save
    c = Category.new(:parent_id => 35);c.id = 122;c.save
    c = Category.new(:parent_id => 35);c.id = 124;c.save
    c = Category.new(:parent_id => 35);c.id = 126;c.save
    c = Category.new(:parent_id => 71);c.id = 127;c.save
    c = Category.new(:parent_id => 44);c.id = 129;c.save
    c = Category.new(:parent_id => 19);c.id = 130;c.save
    c = Category.new(:parent_id => 71);c.id = 133;c.save
    c = Category.new(:parent_id => 18);c.id = 134;c.save
    c = Category.new(:parent_id => 134);c.id = 135;c.save
    c = Category.new(:parent_id => 28);c.id = 136;c.save
    c = Category.new(:parent_id => 28);c.id = 138;c.save
    c = Category.new(:parent_id => 53);c.id = 141;c.save
    c = Category.new(:parent_id => 53);c.id = 142;c.save
    c = Category.new(:parent_id => 80);c.id = 144;c.save
    c = Category.new(:parent_id => 12);c.id = 145;c.save
    c = Category.new(:parent_id => 12);c.id = 147;c.save
    c = Category.new(:parent_id => 36);c.id = 148;c.save
    c = Category.new(:parent_id => 14);c.id = 151;c.save
    c = Category.new(:parent_id => 2757);c.id = 152;c.save
    c = Category.new(:parent_id => 14);c.id = 154;c.save
    c = Category.new(:parent_id => 27);c.id = 157;c.save
    c = Category.new(:parent_id => 27);c.id = 158;c.save
    c = Category.new(:parent_id => 158);c.id = 159;c.save
    c = Category.new(:parent_id => 158);c.id = 161;c.save
    c = Category.new(:parent_id => 158);c.id = 162;c.save
    c = Category.new(:parent_id => 158);c.id = 163;c.save
    c = Category.new(:parent_id => 158);c.id = 164;c.save
    c = Category.new(:parent_id => 168);c.id = 165;c.save
    c = Category.new(:parent_id => 168);c.id = 166;c.save
    c = Category.new(:parent_id => 27);c.id = 168;c.save
    c = Category.new(:parent_id => 39);c.id = 169;c.save
    c = Category.new(:parent_id => 27);c.id = 170;c.save
    c = Category.new(:parent_id => 37);c.id = 190;c.save
    c = Category.new(:parent_id => 37);c.id = 191;c.save
    c = Category.new(:parent_id => 37);c.id = 192;c.save
    c = Category.new(:parent_id => 82);c.id = 193;c.save
    c = Category.new(:parent_id => 16);c.id = 196;c.save
    c = Category.new(:parent_id => 16);c.id = 197;c.save
    c = Category.new(:parent_id => 99);c.id = 200;c.save
    c = Category.new(:parent_id => 99);c.id = 201;c.save
    c = Category.new(:parent_id => 99);c.id = 202;c.save
    c = Category.new(:parent_id => 99);c.id = 204;c.save
    c = Category.new(:parent_id => 99);c.id = 205;c.save
    c = Category.new(:parent_id => 99);c.id = 206;c.save
    c = Category.new(:parent_id => 99);c.id = 208;c.save
    c = Category.new(:parent_id => 878);c.id = 218;c.save
    c = Category.new(:parent_id => 18);c.id = 219;c.save
    c = Category.new(:parent_id => 2738);c.id = 241;c.save
    c = Category.new(:parent_id => 80);c.id = 249;c.save
    c = Category.new(:parent_id => 241);c.id = 250;c.save
    c = Category.new(:parent_id => 80);c.id = 251;c.save
    c = Category.new(:parent_id => 249);c.id = 252;c.save
    c = Category.new(:parent_id => 1);c.id = 878;c.save
    c = Category.new(:parent_id => 1);c.id = 1115;c.save
    c = Category.new(:parent_id => 117);c.id = 1124;c.save
    c = Category.new(:parent_id => 35);c.id = 1125;c.save
    c = Category.new(:parent_id => 35);c.id = 1126;c.save
    c = Category.new(:parent_id => 35);c.id = 1479;c.save
    c = Category.new(:parent_id => 18);c.id = 2370;c.save
    c = Category.new(:parent_id => 1126);c.id = 2712;c.save
    c = Category.new(:parent_id => 35);c.id = 2713;c.save
    c = Category.new(:parent_id => 35);c.id = 2714;c.save
    c = Category.new(:parent_id => 2370);c.id = 2717;c.save
    c = Category.new(:parent_id => 105);c.id = 2729;c.save
    c = Category.new(:parent_id => 28);c.id = 2730;c.save
    c = Category.new(:parent_id => 18);c.id = 2731;c.save
    c = Category.new(:parent_id => 251);c.id = 2737;c.save
    c = Category.new(:parent_id => 80);c.id = 2738;c.save
    c = Category.new(:parent_id => 12);c.id = 2741;c.save
    c = Category.new(:parent_id => 1115);c.id = 2744;c.save
    c = Category.new(:parent_id => 1115);c.id = 2746;c.save
    c = Category.new(:parent_id => 1115);c.id = 2748;c.save
    c = Category.new(:parent_id => 14);c.id = 2757;c.save
    c = Category.new(:parent_id => 14);c.id = 2761;c.save
    c = Category.new(:parent_id => 2757);c.id = 2774;c.save
    c = Category.new(:parent_id => 35);c.id = 2888;c.save
    c = Category.new(:parent_id => 92);c.id = 2889;c.save
    c = Category.new(:parent_id => 18);c.id = 2890;c.save
    c = Category.new(:parent_id => 28);c.id = 2891;c.save
    c = Category.new(:parent_id => 252);c.id = 2892;c.save
    c = Category.new(:parent_id => 252);c.id = 2893;c.save
    c = Category.new(:parent_id => 252);c.id = 2894;c.save
    c = Category.new(:parent_id => 35);c.id = 2915;c.save
    c = Category.new(:parent_id => 1);c.id = 2916;c.save
    c = Category.new(:parent_id => 82);c.id = 2926;c.save
    c = Category.new(:parent_id => 158);c.id = 2932;c.save
    c = Category.new(:parent_id => 878);c.id = 2979;c.save
    c = Category.new(:parent_id => 1115);c.id = 3081;c.save
    c = Category.new(:parent_id => 158);c.id = 3082;c.save
    c = Category.new(:parent_id => 168);c.id = 3083;c.save
    c = Category.new(:parent_id => 36);c.id = 3084;c.save
    c = Category.new(:parent_id => 82);c.id = 3087;c.save
    c = Category.new(:parent_id => 2916);c.id = 3107;c.save
    c = Category.new(:parent_id => 2916);c.id = 3108;c.save
    c = Category.new(:parent_id => 2916);c.id = 3109;c.save
    c = Category.new(:parent_id => 2916);c.id = 3110;c.save
    c = Category.new(:parent_id => 2916);c.id = 3111;c.save
    c = Category.new(:parent_id => 3111);c.id = 3112;c.save
    c = Category.new(:parent_id => 101);c.id = 3113;c.save
    c = Category.new(:parent_id => 101);c.id = 3114;c.save
    c = Category.new(:parent_id => 101);c.id = 3115;c.save
    c = Category.new(:parent_id => 99);c.id = 3117;c.save
    c = Category.new(:parent_id => 99);c.id = 3118;c.save
    c = Category.new(:parent_id => 99);c.id = 3119;c.save
    c = Category.new(:parent_id => 3119);c.id = 3120;c.save
    c = Category.new(:parent_id => 105);c.id = 3172;c.save
    
    
  end
  
  def self.down
    drop_table :categories
  end
end